FROM alpine:latest

# setup source repo, install dependencies
# RUN echo -ne 'https://mirrors.ustc.edu.cn/alpine/edge/main\nhttps://mirrors.ustc.edu.cn/alpine/edge/community\n' > /etc/apk/repositories && \
RUN test -f /etc/apk/repositories.save || cp /etc/apk/repositories /etc/apk/repositories.save
# RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN  \
apk update && apk upgrade && \
apk add --no-cache vim alpine-sdk xz autoconf automake linux-headers clang-dev clang lld libtool cmake && \
apk add --no-cache  ca-certificates openssl openssl-dev curl tini
RUN apk add --no-cache   gnu-libiconv-dev libsodium-dev  libpq-dev bison libxml2-dev  sqlite-dev curl-dev
RUN apk add --no-cache freetype \
      freetype-dev \
      jpeg \
      libpng \
      libwebp \
      libpng \
      libpng-dev \
      libjpeg-turbo \
      libjpeg-turbo-dev \
      gd-dev \
      zlib-dev \
      gmp \
      gmp-dev \
      glib \
      glib-dev \
      libzip-dev
RUN apk add --no-cache   imagemagick
RUN apk add --no-cache php81-dev php81-cli php81-pear php81-curl php81-openssl &&  \
pecl channel-update https://pecl.php.net/channel.xml && pear update-channels
#  postgresql-dev
ENV CC=clang
ENV CXX=clang++
ENV LD=ld.lld
#RUN mv /usr/bin/ld /usr/bin/ld.old && ln -s /usr/bin/ld.lld /usr/bin/ld
WORKDIR /work

RUN rm -rf /var/cache/apk/* /tmp

ENTRYPOINT ["/sbin/tini", "--"]
