version: "3"
services:
    pgadmin4:
        image: dpage/pgadmin4
        container_name: pgadmin4
        ports:
            - "8083:80"
        environment:
            - "PGADMIN_DEFAULT_EMAIL=user@domain.com"
            - "PGADMIN_DEFAULT_PASSWORD=SuperSecret"
            - "PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True"
            - "PGADMIN_CONFIG_LOGIN_BANNER='Authorised users only!'"
            - "PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10"
    adminer: # 可以 链接 pgsql mysql
        image: adminer:latest
        ports:
            - "8080:8080"
    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        ports:
            - "8081:8081"
        extra_hosts:
             - "mongodb-server:192.168.3.26"
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb-server  # 服务名称
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_BASICAUTH_USERNAME: "admin"
            ME_CONFIG_BASICAUTH_PASSWORD: "admin"
        sysctls:
            net.ipv6.conf.all.disable_ipv6: 0
