
FROM alpine:edge as builder
ENV TZ=Etc/UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN test -f /etc/apk/repositories.save || cp /etc/apk/repositories /etc/apk/repositories.save
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

RUN apk update  && apk add tini


WORKDIR /


ADD  ./soruce-code/extensions/ /work/pool/ext/
ADD  ./soruce-code/libraries/ /work/pool/lib/

WORKDIR /work/

