FROM alpine:edge


ENV TZ=Etc/UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN test -f /etc/apk/repositories.save || cp /etc/apk/repositories /etc/apk/repositories.save
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

RUN apk update  && apk add git

WORKDIR /
ARG PROXY_URL=''

ENV http_proxy=$PROXY_URL
ENV https_proxy=$PROXY_URL

RUN git clone -b dev-all-dependency --depth=1 --progress  https://github.com/jingjingxyk/swoole-cli.git

ENV http_proxy=''
ENV https_proxy=''

FROM alpine:edge

COPY --from=0  /swoole-cli  /swoole-cli


