FROM alpine:edge


ENV TZ=Etc/UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN test -f /etc/apk/repositories.save || cp /etc/apk/repositories /etc/apk/repositories.save
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

RUN apk update  && apk add curl wget git   tini ca-certificates openssl openssl-dev

RUN apk add --no-cache php81-dev php81-cli php81-pear php81-curl php81-openssl php81-phar php81-mbstring php81-xmlwriter php81-xml php81-simplexml php81-dom php81-intl php81-tokenizer && apk add --no-cache  icu icu-dev icu-libs icu-data-full icu-static && \
pecl channel-update https://pecl.php.net/channel.xml && pear update-channels && pecl config-show



WORKDIR /
ARG PROXY_URL=""

ENV http_proxy=$PROXY_URL
ENV https_proxy=$PROXY_URL
RUN pear config-set http_proxy $PROXY_URL


RUN git clone -b dev-all-dependency --depth=1 --progress  https://github.com/jingjingxyk/swoole-cli.git


WORKDIR /swoole-cli
RUN git config --global --add safe.directory '*'
RUN git submodule update --init --recursive
# RUN git -C ext/swoole pull --progress
# RUN sh build-tools-scripts/download-init-depend.sh
RUN php prepare.php +inotify +ds
ENV http_proxy=''
ENV https_proxy=''

RUN pear config-set http_proxy ""
# RUN pecl config-show

FROM alpine:edge

COPY --from=0  /swoole-cli/pool  /swoole-cli/pool


