name: dev
services:
  dev:
    image: archlinux:latest
    init: true
    container_name: dev
    hostname: dev
    volumes:
      - .:/workdir
    working_dir: /workdir
    command:
      - bash
      - -c
      - |
        tail -f /dev/null

# 使用最新版的软件