name: artifact-hash

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "发版 版本号 tag"
        default: 'v6.0.0.0'
        type: string
      enable_upload_cloud_object_storage:
        type: choice
        required: true
        options:
          - "0"
          - "1"
        default: '0'
        description: "上传到 cloud object storage (默认不上传到云对象存储）"

jobs:
  generate-artifact-hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show Release File Hash
        run: |
          bash sapi/scripts/generate-artifact-hash.sh --version ${{ inputs.version }}

      - name: production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.version }}-sha256sum
          retention-days: 90
          path: |
            ${{ inputs.version }}-sha256sum

      - name: upload artifacts to cloud object storage
        if: ${{ (github.repository == 'swoole/swoole-cli') &&  inputs.enable_upload_cloud_object_storage }}
        env:
          SECRET_ID: ${{ secrets.QCLOUD_OSS_SECRET_ID }}
          SECRET_KEY: ${{ secrets.QCLOUD_OSS_SECRET_KEY }}
        run: |
          bash sapi/scripts/tencent-cloud-object-storage.sh --upload-all --swoole-cli-version  ${{ inputs.version }}

