name: build-php-cli-linux-amd64

on: [ push, pull_request ]

env:
  BUILD_PHP_VERSION: 7.3.33

jobs:
  linux:
    if: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Source Code
        run: |
          lscpu
          echo $PATH
          env
          docker info
          id -u
          id -g
          who
          cat /etc/os-release
          hostnamectl
          uname -s
          uname -m
          uname -r
          # echo "BUILD_PHP_VERSION=7.3.33" >> "$GITHUB_ENV"
      - name: Prepare Libraries and Extensions
        uses: addnab/docker-run-action@v3
        with:
          image: docker.io/jingjingxyk/build-swoole-cli:download-box-nginx-alpine-20230429T061856Z
          options: -v ${{ github.workspace }}:/work -w /work
          run: |
            set -x
            mkdir -p pool/lib
            mkdir -p pool/ext
            mkdir -p ext
            cp -rf /usr/share/nginx/html/extensions/* pool/ext
            cp -rf /usr/share/nginx/html/libraries/* pool/lib
      - name: Prepare
        uses: addnab/docker-run-action@v3
        with:
          image: docker.io/jingjingxyk/build-swoole-cli:native-php-all-dependencies-alpine-php-7.4-x86_64-20230504T124927Z
          options: -v ${{ github.workspace }}:/work -w /work
          run: |
            pwd
            set -x
            composer update --no-dev  --optimize-autoloader
            php prepare.php  +inotify +apcu +ds -gd -zip -imagick # gd 库 libXpm 编译不成功，libzip 需要降低版本 ，imagick 依赖libzip
            chmod a+x make.sh
            bash ./make.sh curl # 需要重新编译 php7.33 依赖库不包含 nghttp2 (curl nghttp2 与 swoole 里面包含的nghttp2 冲突，保留 swoole 内置的nghttp2)
      - name: Build
        uses: addnab/docker-run-action@v3
        with:
          image: docker.io/jingjingxyk/build-swoole-cli:native-php-all-dependencies-alpine-php-7.4-x86_64-20230504T124927Z
          options: -v ${{ github.workspace }}:/work -w /work -e "BUILD_PHP_VERSION=${{ env.BUILD_PHP_VERSION }}"
          run: |
            ./make.sh config
            ./make.sh build
            ./make.sh archive
            ./php_src/sapi/cli/php -v
            file ./bin/php-${BUILD_PHP_VERSION}/bin/php
            readelf -h ./bin/php-${BUILD_PHP_VERSION}/bin/php
            ./bin/php-${BUILD_PHP_VERSION}/bin/php -r "echo PHP_VERSION;"
      - name: production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: php-cli-linux-x64-${{ env.BUILD_PHP_VERSION }}
          retention-days: 7
          path: ./bin/php-${{ env.BUILD_PHP_VERSION }}/bin/php
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            php-cli-v${{ env.BUILD_PHP_VERSION }}-linux-x64.tar.xz

