name: build-php-cli-macos-x86_64

on: [push, pull_request]

env:
  BUILD_PHP_VERSION: 8.2.4

jobs:
  macos-x86_64:
    if: 0
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure
        run: |

          brew install  wget curl  libtool automake gettext coreutils re2c binutils
          which glibtool
          ln -sf /usr/local/bin/glibtool /usr/local/bin/libtool
          ln -sf /usr/local/bin/glibtoolize /usr/local/bin/libtoolize
          sudo mkdir -p pool/lib
          sudo mkdir -p pool/ext
          echo 'export PATH="/usr/local/opt/binutils/bin:$PATH"' >> /Users/runner/.bash_profile
          source ~/.bash_profile
          env
          echo $HOME
      - name: Cache
        uses: actions/cache@v3
        id: all-archive-cache
        with:
          path: |
            ${GITHUB_WORKSPACE}/var/all-archive.zip
            ${GITHUB_WORKSPACE}/bin/runtime/php
            ${GITHUB_WORKSPACE}/bin/runtime/composer
          key: all-archive
      - name: Prepare runtime
        if: ${{ steps.all-archive-cache.outputs.cache-hit != 'true' }}
        run: |
          sudo mkdir -p pool/lib
          sudo mkdir -p pool/ext
          sudo mkdir -p bin/runtime

          sudo sh  sapi/quickstart/setup-php-runtime.sh
          export PATH=${GITHUB_WORKSPACE}/bin/runtime:$PATH
          sudo sh sapi/download-box/download-box-get-archive-from-server.sh
      - name: prepare
        run: |
          sudo mkdir -p pool/lib
          sudo mkdir -p pool/ext
          sudo mkdir -p bin/runtime
          export PATH=${GITHUB_WORKSPACE}/bin/runtime:$PATH
          sudo sh sapi/download-box/download-box-get-archive-from-server.sh

          sudo composer update --no-dev  --optimize-autoloader
          sudo php prepare.php --without-docker=1  --with-build-type=release  +ds +apcu
      - name: Cache all-library
        uses: actions/cache@v3
        id: all-library-cache
        with:
          path: |
            ${HOME}/.swoole-cli
          key: all-library-cache
      - name: Build all-library
        if: ${{ steps.all-library-cache.outputs.cache-hit != 'true' }}
        run: |
          sudo chmod a+x ./make.sh
          sudo ./make.sh all-library

      - name: Build
        run: |
          sudo chmod a+x ./make.sh
          sudo ./make.sh config
          sudo ./make.sh build
          sudo ./make.sh archive
          # sudo ./thirdparty/php_src/sapi/cli/php -v
          export PATH="/usr/local/opt/binutils/bin:$PATH"
          file ./bin/php-8.2.4/bin/php
          # greadelf -h ./bin/php-8.2.4/bin/php
          ./bin/php-8.2.4/bin/php -r "echo PHP_VERSION;"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: php-cli-macos-x64-8.2.4
          retention-days: 7
          path: ./bin/php-8.2.4/bin/php
      - name: gh release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: php-cli-v8.2.4-macos-x64.tar.xz
          draft: true
          prerelease: true
